[package]
name = "peerstore"
version = "0.1.0"
authors = ["sourcepirate <sathyanarrayanan@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.114"
serde_derive = "1.0.114"